name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: packaging
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE
            README.md
